# Convert a traditional HSPF Model to a mHSP2 Model

Convert a traditional HSPF Model to an HSP2 Model. This is a two-step process.

1. Convert classic HSPF WDM and UCI input files to an HDF5 format file.
    - [pyHSPF](https://github.com/djlampert/PyHSPF): uses the traditional HSPF model input files
2. Modify the internal table structure of the HDF5 file so that the correct outputs can be specified for mHSP2.
    - [HSPsquared](https://github.com/respec/HSPsquared): uses the HDF5 file format and provides utilities for converting from WDM and UCI files to an HDF5 file.

The HSPsquared utilities are used to go from the UCI and WDM file inputs in the traditional HSPF model to an HDF5 file for combined input and output. Once the HDF5 file is created, then need to modify this HDF5 file slightly so that the 'correct' outputs are available for an **mHSP2** model.

## Parameters and Imports

In [1]:
%matplotlib inline

In [2]:
import os
import site
# add in access to the HSPsquared code so that can use the conversion utilities.
site.addsitedir( os.path.normpath( r'C:\Users\nmartin\Documents\HSPsquared-master' ) )

In [3]:
import readWDM, readUCI

In [4]:
uciname = r'C:\Users\nmartin\Documents\Uvalde\NumModel\HSPF\Uvalde14.uci'
wdmname = r'C:\Users\nmartin\Documents\Uvalde\NumModel\HSPF\Uvalde_2_in.wdm'
hdfname = r'C:\Users\nmartin\Documents\Uvalde\NumModel\HSPF\Uvalde14.h5'

In [5]:
import h5py
import pandas as pd
import numpy as np
from IPython.display import display, HTML

## Convert to HSP2 HDF5 Format

In [6]:
# creates HDF5 file (if it doesn't exist) and places UCI data into it
readUCI.readUCI(uciname, hdfname)

In [7]:
# puts all timeseries discovered into HDF5 file with a summary table
readWDM.readWDM(wdmname, hdfname)

11 - [156.875   150.75    148.5     146.      142.25    142.      140.59375
 135.04167 133.71875 158.07292]
12 - [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
13 - [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
31 - [22.726683 22.726683 22.726683 22.726683 22.726683 22.726683 22.726683
 22.726683 22.726683 22.726683]
32 - [2.473972 2.473972 2.473972 2.473972 2.473972 2.473972 2.473972 2.473972
 2.473972 2.473972]
33 - [0.98827714 0.98827714 0.98827714 0.98827714 0.98827714 0.98827714
 0.98827714 0.98827714 0.98827714 0.98827714]
34 - [0.8092711 0.8092711 0.8092711 0.8092711 0.8092711 0.8092711 0.8092711
 0.8092711 0.8092711 0.8092711]
35 - [6.6598334 6.6598334 6.6598334 6.6598334 6.6598334 6.6598334 6.6598334
 6.6598334 6.6598334 6.6598334]
61 - [0.         0.         0.         0.         0.         0.03149606
 0.         0.05629921 0.         0.        ]
81 - [0.07887097 0.07887097 0.07887097 0.07887097 0.07887097 0.07887097
 0.07887097 0.07887097 0.07887097 0.07887097]
101 - [36.6281   38.611572 40.595043 42.578514 44.561985 46.545456 48.342976
 49.865704 49.169422 48.929752]
102 - [1706.8595 1652.1074 1565.5785 1517.3553 1470.4958 1404.3802 1367.8926
 1312.6447 1262.4794 1225.4132]
103 - [163.1405   144.21487  126.44628  119.504135 110.86777  101.11571
  93.84297   85.12397   78.71901   72.35538 ]
104 - [1418.8016 1416.5702 1337.2727 1294.876  1259.8347 1202.3553 1173.5123
 1134.5042 1093.5537 1062.9338]
105 - [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
121 - [ 0.         0.         0.         0.         0.         6.48063
  0.        11.5841255  0.         0.       ]
122 - [0.        0.        0.        0.        0.        3.8465765 0.
 6.8757553 0.        0.       ]
123 - [ 0.        0.        0.        0.        0.       16.297323  0.
 29.131464  0.        0.      ]
124 - [ 0.        0.        0.        0.        0.       20.695013  0.
 36.992336  0.        0.      ]
125 - [ 0.        0.        0.        0.        0.        8.531989  0.
 15.250931  0.        0.      ]
141 - [ 0.        0.        0.        0.        0.       42.330708  0.
 75.666145  0.        0.      ]
142 - [ 0.        0.        0.        0.        0.       15.118111  0.
 27.023623  0.        0.      ]
143 - [ 0.        0.        0.        0.        0.       21.165354  0.
 37.833073  0.        0.      ]
144 - [0.        0.        0.        0.        0.        2.687664  0.
 4.8041997 0.        0.       ]

,Start,Stop,Freq,Length,TSTYPE,TFILL,STNAM,SCENARIO,CONSTITUENT
TS011,2001-01-01 00:00:00,2021-01-01 00:00:00,1D,7305,OUTD,0.0,USGS08192000,INPUT,OUTDGT
TS012,1994-01-01 00:00:00,2021-01-01 00:00:00,1D,9862,OUTD,0.0,USGS08197500,INPUT,OUTDGT
TS013,2003-01-01 00:00:00,2021-01-01 00:00:00,1D,6575,OUTD,0.0,USGS08204005,INPUT,OUTDGT
TS031,2016-01-01 00:00:00,2020-01-01 00:00:00,1D,1461,OUTD,0.0,Edwards_pumping,INPUT,OUTDGT
TS032,2016-01-01 00:00:00,2020-01-01 00:00:00,1D,1461,OUTD,0.0,Austin_pumping,INPUT,OUTDGT
TS033,2016-01-01 00:00:00,2020-01-01 00:00:00,1D,1461,OUTD,0.0,Buda1_pumping,INPUT,OUTDGT
TS034,2016-01-01 00:00:00,2020-01-01 00:00:00,1D,1461,OUTD,0.0,Buda2_pumping,INPUT,OUTDGT
TS035,2016-01-01 00:00:00,2020-01-01 00:00:00,1D,1461,OUTD,0.0,Leona_pumping,INPUT,OUTDGT
TS061,1981-01-01 00:00:00,2021-01-01 00:00:00,1D,14610,PREC,0.0,PRISM daily,INPUT,PREC
TS081,1981-01-01 00:00:00,2021-01-01 00:00:00,1D,14610,EVAP,0.0,PRISM daily,INPUT,EVAP
TS101,2011-01-01 00:00:00,2021-01-01 00:00:00,1D,3653,IVOL,0.0,USGS08189998,INPUT,IVOL
TS102,1992-01-01 00:00:00,2021-01-01 00:00:00,1D,10593,IVOL,0.0,USGS08190000,INPUT,IVOL
TS103,1992-01-01 00:00:00,2021-01-01 00:00:00,1D,10593,IVOL,0.0,USGS08190500,INPUT,IVOL
TS104,1992-01-01 00:00:00,2021-01-01 00:00:00,1D,10593,IVOL,0.0,USGS08195000,INPUT,IVOL
TS105,2012-01-01 00:00:00,2021-01-01 00:00:00,1D,3288,IVOL,0.0,USGS08196300,INPUT,IVOL
TS121,1981-01-01 00:00:00,2021-01-01 00:00:00,1D,14610,IVOL,0.0,Nueces_South,INPUT,IVOL
TS122,1981-01-01 00:00:00,2021-01-01 00:00:00,1D,14610,IVOL,0.0,Nueces_North,INPUT,IVOL
TS123,1981-01-01 00:00:00,2021-01-01 00:00:00,1D,14610,IVOL,0.0,Leona_River,INPUT,IVOL
TS124,1981-01-01 00:00:00,2021-01-01 00:00:00,1D,14610,IVOL,0.0,Dry Frio,INPUT,IVOL
TS125,1981-01-01 00:00:00,2021-01-01 00:00:00,1D,14610,IVOL,0.0,Frio,INPUT,IVOL
TS141,1981-01-01 00:00:00,2021-01-01 00:00:00,1D,14610,IVOL,0.0,Edwards_Recharge,INPUT,IVOL
TS142,1981-01-01 00:00:00,2021-01-01 00:00:00,1D,14610,IVOL,0.0,Austin_Recharge,INPUT,IVOL
TS143,1981-01-01 00:00:00,2021-01-01 00:00:00,1D,14610,IVOL,0.0,Buda_Recharge,INPUT,IVOL
TS144,1981-01-01 00:00:00,2021-01-01 00:00:00,1D,14610,IVOL,0.0,Leona_Recharge,INPUT,IVOL

## Make Modifications for mHSP2

The following is equivalent to the mHSP2 "Set the 'Save' Parameters to HDF5" notebook in the **pyHS2MF6** repository.

In [8]:
PERLND_OUTPUTs = [ "AGWET", "AGWI", "AGWO", "AGWS", "BASET", "CEPE", 
                     "CEPS", "GWVS", "IFWI", "IFWO", "IFWS", "IGWI",
                     "INFFAC", "INFIL", "LZET", "LZI", "LZS", "RPARM", 
                     "PERC", "PERO", "PERS", "PET", "SUPY", 
                     "SURI", "SURO", "SURS", "TAET", "TGWS", "UZET", 
                     "UZI", "UZS" ]

In [9]:
IMPLND_OUTPUTs = [ "IMPEV", "IMPS", "PET", "RETS", "SUPY", "SURI", 
                     "SURO", "SURS" ]

In [10]:
RCHRES_OUTPUTs = [ "AVDEP", "AVVEL", "DEP", "HRAD", "IVOL", "O1", 
                     "O2", "O3", "O4", "O5", "OVOL1", "OVOL2", 
                     "OVOL3", "OVOL4", "OVOL5", "PRSUPY", "RO", 
                     "ROVOL", "SAREA", "STAGE", "VOL", "TAU", 
                     "TWID", "USTAR", "VOLEV" ]

### Determine the HDF5 Format

In [11]:
GTABLE_PATH = '/CONTROL/GLOBAL/table'
UNITS_STR = 'units'
OldFmt = 0
NewFmt = 1
# locals
FoundUnits = False
# start
chkFile = h5py.File(hdfname, 'r')
globs = chkFile[GTABLE_PATH]
NRows = globs.shape[0]
for iI in range(NRows):
    testStr = globs[iI][0]
    utStr = testStr.decode()
    if utStr == UNITS_STR:
        FoundUnits = True
        break
    # end if
# end for
# close the file
chkFile.close()
# set the units
if FoundUnits:
    HDF_FMT = OldFmt
else:
    HDF_FMT = NewFmt
# end if
if HDF_FMT == 0:
    print("Old or original format HDF5 file")
else:
    print("New or modified format HDF5 file")

New or modified format HDF5 file

### New Format Modifications

In [12]:
with pd.HDFStore( hdfname ) as store:
    opsDF = store.get( "/CONTROL/OP_SEQUENCE/" )
# end with and close HDF5 file

In [13]:
display( HTML( opsDF.to_html() ) )

In [14]:
TARG_DICT = dict()
for index, row in opsDF.iterrows():
    cKey = str( row['OPERATION'] )
    cVal = str( row['SEGMENT'] )
    if cKey in TARG_DICT.keys():
        TARG_DICT[cKey].append( cVal )
    else:
        TARG_DICT[cKey] = [ cVal ]
    # end if
# end for

In [15]:
TARG_DICT

{'RCHRES': ['R004',
  'R006',
  'R008',
  'R001',
  'R002',
  'R010',
  'R003',
  'R009',
  'R005',
  'R007']}

In [16]:
GOOD_TARGS = [ 'PERLND', 'IMPLND', 'RCHRES' ]

#### PERLND

In [17]:
tTarg = GOOD_TARGS[0]
tIDs = sorted( TARG_DICT[tTarg ] )
NumIDs = len( tIDs )
Vals = np.ones( NumIDs, dtype=np.int32 )

KeyError: 'PERLND'

No PERLND in this model so nothing to do.

#### IMPLND

In [18]:
tTarg = GOOD_TARGS[1]
tIDs = sorted( TARG_DICT[tTarg ] )
NumIDs = len( tIDs )
Vals = np.ones( NumIDs, dtype=np.int32 )

KeyError: 'IMPLND'

No IMPLND so nothing to do

#### RCHRES

In [19]:
tTarg = GOOD_TARGS[2]
tIDs = sorted( TARG_DICT[tTarg ] )
NumIDs = len( tIDs )
Vals = np.ones( NumIDs, dtype=np.int32 )

In [20]:
DataDict = dict()
for tHdr in RCHRES_OUTPUTs:
    DataDict[tHdr] = Vals
# end for
woDF = pd.DataFrame( index=tIDs, data=DataDict )

In [21]:
display( HTML( woDF.to_html() ) )

In [22]:
with h5py.File(hdfname, 'a') as h5:
    del h5["/RCHRES/HYDR/SAVE/"]
# end with

In [23]:
with pd.HDFStore( hdfname ) as store:
    store.put( key="/RCHRES/HYDR/SAVE/", value=woDF, format='table', index=True, data_columns=True )
# end with